crudengold/-venuebookr

app/controllers/pages_controller.rb, app/views/pages/home.html.erb, config/routes.rb, db/schema.rb, test/controllers/pages_controller_test.rb
I have created the Pages controller, put a 'home' method wthin this and also set up the home view. This worked in my rails server.
=> created pages controller and home page

Gemfile, Gemfile.lock, app/controllers/users_controller.rb, app/models/user.rb, app/views/devise/confirmations/new.html.erb, app/views/devise/mailer/confirmation_instructions.html.erb, app/views/devise/mailer/email_changed.html.erb, app/views/devise/mailer/password_change.html.erb, app/views/devise/mailer/reset_password_instructions.html.erb, app/views/devise/mailer/unlock_instructions.html.erb, app/views/devise/passwords/edit.html.erb, app/views/devise/passwords/new.html.erb, app/views/devise/registrations/edit.html.erb, app/views/devise/registrations/new.html.erb, app/views/devise/sessions/new.html.erb, app/views/devise/shared/_error_messages.html.erb, app/views/devise/shared/_links.html.erb, app/views/devise/unlocks/new.html.erb, app/views/layouts/application.html.erb, app/views/pages/home.html.erb, config/environments/development.rb, config/initializers/devise.rb, config/locales/devise.en.yml, config/routes.rb, db/migrate/20231120165743_devise_create_users.rb, db/schema.rb, test/controllers/users_controller_test.rb, test/models/user_test.rb
I've created a user controller,  model with its set attributrions and view with devise signin/signup.
=> Creating user model

app/controllers/venues_controller.rb, app/models/venue.rb, app/views/venues/index.html.erb, app/views/venues/new.html.erb, config/routes.rb, db/migrate/20231120162835_create_venues.rb, db/migrate/20231120163218_add_attributes_to_venues.rb, db/schema.rb, test/controllers/venue_controller_test.rb, test/controllers/venues_controller_test.rb, test/models/venue_test.rb
I have created a venue model with all the attributes we agreed on
I also created the venue controller, with the index, new and create methods
=> Add venues model and controller

.gitignore, Gemfile, Gemfile.lock, app/controllers/venues_controller.rb, app/models/venue.rb, app/views/layouts/application.html.erb, app/views/venues/_form.html.erb, app/views/venues/new.html.erb, app/views/venues/show.html.erb, config/environments/development.rb, config/storage.yml, db/migrate/20231121124559_create_active_storage_tables.active_storage.rb, db/schema.rb
I have tweaked the venue creation form. it still looks bad, but it works now. And I have added the ability for photos to be uploaded (though not yet for them to be displayed)
Jon and I thought it would be useful for us to push our branches as they are before lunch, as it would be useful to be able to see each others work as we carry on this afternoon
=> Venue creation form

app/models/user.rb, app/models/venue.rb, app/views/devise/registrations/new.html.erb, app/views/devise/sessions/new.html.erb, app/views/venues/_form.html.erb
I've changed the styling on the forms for:
- new venue
- log in
- sign up
The buttons on each form still don't look right though
=> Forms look nicer now

app/assets/stylesheets/application.scss, app/assets/stylesheets/components/_footer.scss, app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/pages/_home.scss, app/views/layouts/application.html.erb, app/views/pages/home.html.erb, app/views/shared/_footer.html.erb
Moved footer from homepage to shared partial so that it can display on all pages
=> footer universal and pinned to bottom of screen

app/controllers/venues_controller.rb, db/migrate/20231121162503_add_user_to_venues.rb, db/schema.rb
I changed the new venue form so that you can only submit it if you are signed in, and once you do, the venue is assigned to the user
=> Worked on users and new venue form

Gemfile, Gemfile.lock, app/models/user.rb, db/seeds.rb
I've created a seed file that generates:
- 5 users with an email and password 123456
- 10 businesses with all the relevant details and a user assigned
=> New seed file

app/views/venues/show.html.erb
fixed bug in show, know allows user to attach as many or no photos  to venue page :)
=> Fixed bug do with image attachments in show

app/views/shared/_navbar.html.erb
'Become a host' button now redirects user to the login page if they are not already logged in
=> Reroute unknown user

app/views/venues/index.html.erb, app/views/venues/show.html.erb
Sligtly imporved UI on index/show - cards now clickable instead of button - bit cleaner look on show, still need to center image in show page.
=> Improving UI/index/show

app/controllers/bookings_controller.rb, app/javascript/controllers/datepicker_controller.js, app/models/user.rb, app/views/bookings/_booking_form.html.erb, app/views/bookings/new.html.erb, app/views/layouts/application.html.erb, config/importmap.rb, config/routes.rb
Booking form has been created and works (only inputs currently are start and end date)
Submitting the booking form creates the booking, with user and venue attached
I also updated the routes, so that a user's bookings can be indexed and shown
Updated the bookings controller with index and show methods
=> Booking form

app/views/venues/show.html.erb, config/environments/production.rb
I replaced :local by :cloudinary for the production environment
=> Replaced :local by :cloudinary for the production environment

app/controllers/pages_controller.rb, app/views/bookings/index.html.erb, app/views/pages/dashboard.html.erb, config/routes.rb
Created a user dashboard (within 'pages')
This will only be visible when user is logged in, and we can pass in current_user
Then if user has bookings, they will be displayed here
=> creating user dashboard to display bookings

app/views/venues/show.html.erb
Rounded edges on carousel images - made div size so images will not overspill, and will stretch to fill if smaller than div. Created airbnb-style box for text.
=> styling on text and carousel

app/controllers/bookings_controller.rb
just a little one: changed the bookings#new method to redirect to the dashboard when a booking is made
=> new booking now redirects to dashboard

app/controllers/venues_controller.rb, app/views/venues/show.html.erb
I created a render to connect the booking form onto the venue show page. 
I added a booking instance into the venues controller.
=> Adding booking forms to the venue show page

app/controllers/pages_controller.rb, app/views/pages/_venue.html.erb, app/views/pages/home.html.erb
The home page now displays an index of all venues
=> Combine home and index

app/assets/stylesheets/pages/_home.scss, app/controllers/pages_controller.rb, app/models/venue.rb, app/views/pages/_venue.html.erb, app/views/pages/home.html.erb, db/seeds.rb
The seed file is now better and includes images (just one per venue, mind)
=> Make seed better

app/views/pages/dashboard.html.erb, app/views/venues/index.html.erb, app/views/venues/show.html.erb
Created basic UI for dashboard both displaying the bookings and venues of a user. Also added price calculations for bookings showing days booked out for and price for total. Also changed text from "per hour" to display "per day" as i price is calculated/booked per day :)
=> improved UI + price displayed dashboard

app/views/pages/_venue.html.erb, app/views/venues/_form.html.erb
changed "price per hour" to "price per day" in a few places
=> Homepage tweak

app/views/pages/home.html.erb, app/views/shared/_navbar.html.erb
- Added a search bar into the homepages - to get the search function 
- Improved the placeholder text 
- Removed the login + signup buttons from the homepage
=> Removing login and signup from hero landing page

app/assets/stylesheets/components/_dropdown.scss, app/assets/stylesheets/components/_index.scss, app/views/shared/_navbar.html.erb, app/views/venues/show.html.erb
Added a dropdown when clicking the user avatar - links to dashboard & sign out. Sign out functionality working. Also added "VenueBookr" text next to logo
=> navbar dropdown function added

Gemfile, Gemfile.lock, app/controllers/venues_controller.rb, app/models/venue.rb, app/views/pages/home.html.erb
- Added pg gems 
- Updated the search form to contain params in the form homepage
- Added pg search for one model including venue name and location 
- Created a statement for when params are searched to showcase this else will show all venues
- Update the search input to match colour scheme and giving the appropriate placeholder
=> To create a functioning search using pg search

app/views/shared/_navbar.html.erb
- Created a statement in navbar where the search form only shows up if in the pages controller and action home so that it does not show on the homepage.
=> removed the search bar in the homepage navbar but kept on other pages

app/controllers/bookmarks_controller.rb, app/views/bookmarks/_bookmark_form.html.erb, db/schema.rb
Complete bookmarking function, flick switch to add bookmark and unswitch to delete bookmark - still futher UI change - current switch is blue will look to change to the red seen throughout site
=> Bookmark function complete

app/assets/stylesheets/components/_banner.scss, app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_navbar.scss, app/assets/stylesheets/pages/_home.scss, app/views/pages/home.html.erb, app/views/shared/_navbar.html.erb
Made some adjustments to the look of the hero page, changes included.
- changed the copy and size
- changed the colour
=> Improving the design look of the homepage

app/assets/stylesheets/application.scss, app/views/devise/registrations/new.html.erb, app/views/devise/sessions/new.html.erb
Added the banner image to the page background, and made the forms a bit neater
=> styling for login and sign up forms

app/assets/stylesheets/pages/_home.scss, app/controllers/venues_controller.rb, app/views/venues/_venue.html.erb, app/views/venues/index.html.erb, app/views/venues/show.html.erb
Maps in the show and index pages
on index page it is sticky and to the side of the index
Also moved the booking form to the right of show photos and made it sticky, but it currently stops part way down
=> Add map to show page

app/views/bookings/_booking_form.html.erb, app/views/pages/dashboard.html.erb, app/views/venues/_form.html.erb
Form buttons are now red and have words like 'Book' instead of create booking
=> forms look nicer, buttons are more descriptive

app/views/shared/_navbar.html.erb
- enabled navbar to be searched
=> Search in nav bar on other pages had been fixed/functioning

app/views/pages/dashboard.html.erb, db/migrate/20231124112500_add_name_to_users.rb, db/migrate/20231124112719_addlast_name_to_users.rb, db/schema.rb
- Added first name and last name into the schema -migrated
=> Adding firstname and lastname to users and display in dashboard

app/assets/stylesheets/components/_address_autocomplete.scss, app/assets/stylesheets/pages/_dashboard.scss, app/assets/stylesheets/pages/_index.scss, app/javascript/controllers/tabs_controller.js, app/views/bookings/_booking_form.html.erb, app/views/pages/dashboard.html.erb
Tabs for venues, booking and bookmarks, it looks pretty good if I do say so myself
=> Tabs in dashboard

app/controllers/bookings_controller.rb, app/controllers/bookmarks_controller.rb, app/controllers/venues_controller.rb, app/views/pages/dashboard.html.erb, app/views/shared/_flash.html.erb, app/views/venues/show.html.erb
Added succesful alerts for venue creartion, bookings and saves ! -
=> Added succesful alerts 

app/views/bookings/_booking_form.html.erb, app/views/venues/show.html.erb
Made UI improvements to UI page and booking form given things more spacing and centred
=> Changes to show page and booking form

app/controllers/application_controller.rb, app/views/pages/dashboard.html.erb
- Added firstname and lastname - updated the dashboard welcome name section
=> Added attributes to uses to the application controller 

app/views/pages/_venue.html.erb, db/seeds.rb
review generation section added to seed file. Changed made to pages>_venue.html.erb to display average rating on the cards on the homepage - to be added to index page
=> generated random reviews and displayed average on homepage cards

app/views/bookmarks/_bookmark_form.html.erb
Fixed bug that would crash website on show when there was no one logged in becuase of boookmark form render !
=> Bookmark bug fixed when user not signed in 

app/assets/stylesheets/application.scss
Made slight UI improvement to save switch
=> Small UI changes to save switch

app/assets/stylesheets/pages/_home.scss, app/views/pages/_venue.html.erb, app/views/venues/_venue.html.erb, app/views/venues/show.html.erb
booking form is sticky and looks good. some other minor format tweaks on home page to be consistent with index page
=> Sticky booking form

app/views/venues/_info_window.html.erb
Map info now takes you to show ! + has red border / tookout description as often overflowed card
=> Allowed maps to be clickable
